---
Name: webpack_requirements_backend
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\WebpackRequirementsBackend\Control\WebpackPageControllerExtension

Sunnysideup\WebpackRequirementsBackend\View\RequirementsBackendForWebpack:
  domains_to_ignore:
    - "fonts.googleapis.com"
    - "maps.googleapis.com"
  files_starts_with_ignore:
    - vendor/silverstripe
    - vendor/undefinedoffset/silverstripe-nocaptcha
    - vendor/lekoala/silverstripe-debugbar
  files_to_ignore:
    #js
    - "vendor/sunnysideup/elemental-edit-me-button/client/AddCanEditButton.js"
    - "vendor/undefinedoffset/silverstripe-nocaptcha/javascript/NocaptchaField.js"
    # css
    - "vendor/sunnysideup/elemental-edit-me-button/client/AddCanEditButton.css"
